# Generated by Django 3.2 on 2023-02-16 05:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=120)),
                ('job_description', models.TextField()),
                ('job_publish', models.DateTimeField(default=datetime.datetime(2023, 2, 16, 5, 39, 55, 733634, tzinfo=utc))),
                ('job_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'm_job',
                'ordering': ['-job_publish'],
            },
        ),
    ]
