# Generated by Django 3.2 on 2023-02-16 05:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
